// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $animal from "./routes/animal.tsx";
import * as $event from "./routes/event.tsx";
import * as $index from "./routes/index.tsx";
import * as $location from "./routes/location.tsx";
import * as $search from "./routes/search.tsx";
import * as $Footer from "./islands/Footer.tsx";
import * as $Form from "./islands/Form.tsx";
import * as $Header from "./islands/Header.tsx";
import * as $Search from "./islands/Search.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/animal.tsx": $animal,
    "./routes/event.tsx": $event,
    "./routes/index.tsx": $index,
    "./routes/location.tsx": $location,
    "./routes/search.tsx": $search,
  },
  islands: {
    "./islands/Footer.tsx": $Footer,
    "./islands/Form.tsx": $Form,
    "./islands/Header.tsx": $Header,
    "./islands/Search.tsx": $Search,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
